/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Mixin to filter querysets by the user's school.
         *     Superadmins can see everything.
         */
        get: operations["alerts_list"];
        put?: never;
        /**
         * @description Mixin to filter querysets by the user's school.
         *     Superadmins can see everything.
         */
        post: operations["alerts_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Mixin to filter querysets by the user's school.
         *     Superadmins can see everything.
         */
        get: operations["alerts_retrieve"];
        /**
         * @description Mixin to filter querysets by the user's school.
         *     Superadmins can see everything.
         */
        put: operations["alerts_update"];
        post?: never;
        /**
         * @description Mixin to filter querysets by the user's school.
         *     Superadmins can see everything.
         */
        delete: operations["alerts_destroy"];
        options?: never;
        head?: never;
        /**
         * @description Mixin to filter querysets by the user's school.
         *     Superadmins can see everything.
         */
        patch: operations["alerts_partial_update"];
        trace?: never;
    };
    "/api/alerts/{id}/resolve/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Mixin to filter querysets by the user's school.
         *     Superadmins can see everything.
         */
        post: operations["alerts_resolve_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/token/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a set of user credentials and returns an access and refresh JSON web
         *     token pair to prove the authentication of those credentials.
         */
        post: operations["auth_token_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/token/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a refresh type JSON web token and returns an access type JSON web
         *     token if the refresh token is valid.
         */
        post: operations["auth_token_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/buses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Mixin to filter querysets by the user's school.
         *     Superadmins can see everything.
         */
        get: operations["buses_list"];
        put?: never;
        /**
         * @description Mixin to filter querysets by the user's school.
         *     Superadmins can see everything.
         */
        post: operations["buses_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/buses/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Mixin to filter querysets by the user's school.
         *     Superadmins can see everything.
         */
        get: operations["buses_retrieve"];
        /**
         * @description Mixin to filter querysets by the user's school.
         *     Superadmins can see everything.
         */
        put: operations["buses_update"];
        post?: never;
        /**
         * @description Mixin to filter querysets by the user's school.
         *     Superadmins can see everything.
         */
        delete: operations["buses_destroy"];
        options?: never;
        head?: never;
        /**
         * @description Mixin to filter querysets by the user's school.
         *     Superadmins can see everything.
         */
        patch: operations["buses_partial_update"];
        trace?: never;
    };
    "/api/buses/{id}/update_status/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Update just the bus status. */
        post: operations["buses_update_status_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/buses/online/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Return only online buses for the school. */
        get: operations["buses_online_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Mixin to filter querysets by the user's school.
         *     Superadmins can see everything.
         */
        get: operations["gps_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gps/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Mixin to filter querysets by the user's school.
         *     Superadmins can see everything.
         */
        get: operations["gps_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gps/telemetry/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Update GPS point for a bus (called by TCP gateway). */
        post: operations["gps_telemetry_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gps/bulk_telemetry/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Batch update for GPS points (called by smarter Gateway). */
        post: operations["gps_bulk_telemetry_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gps/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Return cumulative KM series per bus, computed in PostGIS. */
        get: operations["gps_timeline"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gps/latest/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Return latest GPS point for every bus in the school. */
        get: operations["gps_latest_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/routes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Mixin to filter querysets by the user's school.
         *     Superadmins can see everything.
         */
        get: operations["routes_list"];
        put?: never;
        /**
         * @description Mixin to filter querysets by the user's school.
         *     Superadmins can see everything.
         */
        post: operations["routes_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/routes/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Mixin to filter querysets by the user's school.
         *     Superadmins can see everything.
         */
        get: operations["routes_retrieve"];
        /**
         * @description Mixin to filter querysets by the user's school.
         *     Superadmins can see everything.
         */
        put: operations["routes_update"];
        post?: never;
        /**
         * @description Mixin to filter querysets by the user's school.
         *     Superadmins can see everything.
         */
        delete: operations["routes_destroy"];
        options?: never;
        head?: never;
        /**
         * @description Mixin to filter querysets by the user's school.
         *     Superadmins can see everything.
         */
        patch: operations["routes_partial_update"];
        trace?: never;
    };
    "/api/schools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Mixin to filter querysets by the user's school.
         *     Superadmins can see everything.
         */
        get: operations["schools_list"];
        put?: never;
        /**
         * @description Mixin to filter querysets by the user's school.
         *     Superadmins can see everything.
         */
        post: operations["schools_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schools/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Mixin to filter querysets by the user's school.
         *     Superadmins can see everything.
         */
        get: operations["schools_retrieve"];
        /**
         * @description Mixin to filter querysets by the user's school.
         *     Superadmins can see everything.
         */
        put: operations["schools_update"];
        post?: never;
        /**
         * @description Mixin to filter querysets by the user's school.
         *     Superadmins can see everything.
         */
        delete: operations["schools_destroy"];
        options?: never;
        head?: never;
        /**
         * @description Mixin to filter querysets by the user's school.
         *     Superadmins can see everything.
         */
        patch: operations["schools_partial_update"];
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Mixin to filter querysets by the user's school.
         *     Superadmins can see everything.
         */
        get: operations["users_list"];
        put?: never;
        /**
         * @description Mixin to filter querysets by the user's school.
         *     Superadmins can see everything.
         */
        post: operations["users_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Mixin to filter querysets by the user's school.
         *     Superadmins can see everything.
         */
        get: operations["users_retrieve"];
        /**
         * @description Mixin to filter querysets by the user's school.
         *     Superadmins can see everything.
         */
        put: operations["users_update"];
        post?: never;
        /**
         * @description Mixin to filter querysets by the user's school.
         *     Superadmins can see everything.
         */
        delete: operations["users_destroy"];
        options?: never;
        head?: never;
        /**
         * @description Mixin to filter querysets by the user's school.
         *     Superadmins can see everything.
         */
        patch: operations["users_partial_update"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Alert: {
            /** Format: uuid */
            readonly id: string;
            readonly bus: components["schemas"]["BusList"];
            type: components["schemas"]["AlertTypeEnum"];
            message: string;
            is_resolved?: boolean;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: uuid */
            resolved_by?: string | null;
        };
        /**
         * @description * `sos` - SOS
         *     * `overspeed` - Overspeed
         *     * `off_route` - Off Route
         *     * `camera_offline` - Camera Offline
         *     * `student_missing` - Student Missing
         * @enum {string}
         */
        AlertTypeEnum: "sos" | "overspeed" | "off_route" | "camera_offline" | "student_missing";
        BusDetail: {
            /** Format: uuid */
            readonly id: string;
            readonly route: components["schemas"]["Route"];
            readonly school: components["schemas"]["School"];
            internal_id: string;
            plate_number: string;
            status?: components["schemas"]["StatusEnum"];
            camera_count?: number;
            router_ip?: string | null;
            driver_name?: string;
            driver_phone?: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            /** Format: uuid */
            transporter?: string | null;
        };
        BusList: {
            /** Format: uuid */
            readonly id: string;
            internal_id: string;
            plate_number: string;
            status?: components["schemas"]["StatusEnum"];
            /** Format: double */
            readonly lat: number;
            /** Format: double */
            readonly lng: number;
            readonly route_name: string;
            driver_name?: string;
        };
        GPSPoint: {
            readonly id: number;
            /** Format: double */
            lat: number;
            /** Format: double */
            lng: number;
            /** Format: double */
            speed?: number;
            /** Format: double */
            heading?: number;
            /** Format: double */
            accuracy?: number | null;
            /** Format: date-time */
            timestamp: string;
            /** Format: uuid */
            bus: string;
        };
        PaginatedAlertList: {
            /** @example 123 */
            count?: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results?: components["schemas"]["Alert"][];
        };
        PaginatedBusListList: {
            /** @example 123 */
            count?: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results?: components["schemas"]["BusList"][];
        };
        PaginatedGPSPointList: {
            /** @example 123 */
            count?: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results?: components["schemas"]["GPSPoint"][];
        };
        PaginatedRouteList: {
            /** @example 123 */
            count?: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results?: components["schemas"]["Route"][];
        };
        PaginatedSchoolList: {
            /** @example 123 */
            count?: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results?: components["schemas"]["School"][];
        };
        PaginatedUserList: {
            /** @example 123 */
            count?: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results?: components["schemas"]["User"][];
        };
        PatchedAlert: {
            /** Format: uuid */
            readonly id?: string;
            readonly bus?: components["schemas"]["BusList"];
            type?: components["schemas"]["AlertTypeEnum"];
            message?: string;
            is_resolved?: boolean;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: uuid */
            resolved_by?: string | null;
        };
        PatchedBusDetail: {
            /** Format: uuid */
            readonly id?: string;
            readonly route?: components["schemas"]["Route"];
            readonly school?: components["schemas"]["School"];
            internal_id?: string;
            plate_number?: string;
            status?: components["schemas"]["StatusEnum"];
            camera_count?: number;
            router_ip?: string | null;
            driver_name?: string;
            driver_phone?: string;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
            /** Format: uuid */
            transporter?: string | null;
        };
        PatchedRoute: {
            /** Format: uuid */
            readonly id?: string;
            name?: string;
            type?: components["schemas"]["RouteTypeEnum"];
            is_active?: boolean;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: uuid */
            school?: string;
            /** Format: uuid */
            transporter?: string | null;
        };
        PatchedSchool: {
            /** Format: uuid */
            readonly id?: string;
            name?: string;
            address?: string;
            /** Format: email */
            contact_email?: string;
            phone?: string;
            is_active?: boolean;
        };
        PatchedUser: {
            /** Format: uuid */
            readonly id?: string;
            /** Format: email */
            email?: string;
            full_name?: string;
            role?: components["schemas"]["RoleEnum"];
            /** Format: uuid */
            school?: string | null;
            /** Format: uuid */
            transporter?: string | null;
            /** Format: uri */
            photo_url?: string;
        };
        /**
         * @description * `superadmin` - Super Admin
         *     * `transporter` - Transporter
         *     * `school_admin` - School Admin
         *     * `parent` - Parent
         * @enum {string}
         */
        RoleEnum: "superadmin" | "transporter" | "school_admin" | "parent";
        Route: {
            /** Format: uuid */
            readonly id: string;
            name: string;
            type?: components["schemas"]["RouteTypeEnum"];
            is_active?: boolean;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: uuid */
            school: string;
            /** Format: uuid */
            transporter?: string | null;
        };
        /**
         * @description * `morning` - Morning
         *     * `afternoon` - Afternoon
         *     * `custom` - Custom
         * @enum {string}
         */
        RouteTypeEnum: "morning" | "afternoon" | "custom";
        School: {
            /** Format: uuid */
            readonly id: string;
            name: string;
            address?: string;
            /** Format: email */
            contact_email?: string;
            phone?: string;
            is_active?: boolean;
        };
        /**
         * @description * `online` - Online
         *     * `offline` - Offline
         *     * `idle` - Idle
         * @enum {string}
         */
        StatusEnum: "online" | "offline" | "idle";
        TokenObtainPair: {
            email: string;
            password: string;
            readonly access: string;
            readonly refresh: string;
        };
        TokenRefresh: {
            readonly access: string;
            refresh: string;
        };
        User: {
            /** Format: uuid */
            readonly id: string;
            /** Format: email */
            email: string;
            full_name: string;
            role?: components["schemas"]["RoleEnum"];
            /** Format: uuid */
            school?: string | null;
            /** Format: uuid */
            transporter?: string | null;
            /** Format: uri */
            photo_url?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    alerts_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedAlertList"];
                };
            };
        };
    };
    alerts_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Alert"];
                "application/x-www-form-urlencoded": components["schemas"]["Alert"];
                "multipart/form-data": components["schemas"]["Alert"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Alert"];
                };
            };
        };
    };
    alerts_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this alert. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Alert"];
                };
            };
        };
    };
    alerts_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this alert. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Alert"];
                "application/x-www-form-urlencoded": components["schemas"]["Alert"];
                "multipart/form-data": components["schemas"]["Alert"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Alert"];
                };
            };
        };
    };
    alerts_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this alert. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    alerts_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this alert. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedAlert"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedAlert"];
                "multipart/form-data": components["schemas"]["PatchedAlert"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Alert"];
                };
            };
        };
    };
    alerts_resolve_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this alert. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Alert"];
                "application/x-www-form-urlencoded": components["schemas"]["Alert"];
                "multipart/form-data": components["schemas"]["Alert"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Alert"];
                };
            };
        };
    };
    auth_token_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenObtainPair"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenObtainPair"];
                "multipart/form-data": components["schemas"]["TokenObtainPair"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenObtainPair"];
                };
            };
        };
    };
    auth_token_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefresh"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenRefresh"];
                "multipart/form-data": components["schemas"]["TokenRefresh"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenRefresh"];
                };
            };
        };
    };
    buses_list: {
        parameters: {
            query?: {
                internal_id?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                route?: string;
                /**
                 * @description * `online` - Online
                 *     * `offline` - Offline
                 *     * `idle` - Idle
                 */
                status?: "idle" | "offline" | "online";
                transporter?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedBusListList"];
                };
            };
        };
    };
    buses_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BusDetail"];
                "application/x-www-form-urlencoded": components["schemas"]["BusDetail"];
                "multipart/form-data": components["schemas"]["BusDetail"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BusDetail"];
                };
            };
        };
    };
    buses_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this bus. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BusDetail"];
                };
            };
        };
    };
    buses_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this bus. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BusDetail"];
                "application/x-www-form-urlencoded": components["schemas"]["BusDetail"];
                "multipart/form-data": components["schemas"]["BusDetail"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BusDetail"];
                };
            };
        };
    };
    buses_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this bus. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    buses_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this bus. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedBusDetail"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedBusDetail"];
                "multipart/form-data": components["schemas"]["PatchedBusDetail"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BusDetail"];
                };
            };
        };
    };
    buses_update_status_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this bus. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BusDetail"];
                "application/x-www-form-urlencoded": components["schemas"]["BusDetail"];
                "multipart/form-data": components["schemas"]["BusDetail"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BusDetail"];
                };
            };
        };
    };
    buses_online_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BusDetail"];
                };
            };
        };
    };
    gps_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedGPSPointList"];
                };
            };
        };
    };
    gps_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this gps point. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GPSPoint"];
                };
            };
        };
    };
    gps_telemetry_create: {
        parameters: {
            query?: never;
            header: {
                "X-API-KEY": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    imei?: string;
                    lat?: number;
                    lng?: number;
                    speed?: number;
                    heading?: number;
                    ignition?: boolean;
                    timestamp?: number;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status?: string;
                    };
                };
            };
        };
    };
    gps_bulk_telemetry_create: {
        parameters: {
            query?: never;
            header: {
                "X-API-KEY": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    imei?: string;
                    coords?: number[];
                    speed?: number;
                    heading?: number;
                    ignition?: boolean;
                    timestamp?: number;
                }[];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status?: string;
                        count?: number;
                    };
                };
            };
        };
    };
    gps_timeline: {
        parameters: {
            query?: {
                start?: string;
                end?: string;
                bus?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        bus_id?: string;
                        internal_id?: string;
                        series?: {
                            /** Format: date-time */
                            timestamp?: string;
                            cumulative_km?: number;
                        }[];
                    }[];
                };
            };
        };
    };
    gps_latest_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GPSPoint"];
                };
            };
        };
    };
    routes_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedRouteList"];
                };
            };
        };
    };
    routes_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Route"];
                "application/x-www-form-urlencoded": components["schemas"]["Route"];
                "multipart/form-data": components["schemas"]["Route"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Route"];
                };
            };
        };
    };
    routes_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this route. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Route"];
                };
            };
        };
    };
    routes_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this route. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Route"];
                "application/x-www-form-urlencoded": components["schemas"]["Route"];
                "multipart/form-data": components["schemas"]["Route"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Route"];
                };
            };
        };
    };
    routes_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this route. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    routes_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this route. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedRoute"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedRoute"];
                "multipart/form-data": components["schemas"]["PatchedRoute"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Route"];
                };
            };
        };
    };
    schools_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedSchoolList"];
                };
            };
        };
    };
    schools_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["School"];
                "application/x-www-form-urlencoded": components["schemas"]["School"];
                "multipart/form-data": components["schemas"]["School"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["School"];
                };
            };
        };
    };
    schools_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this school. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["School"];
                };
            };
        };
    };
    schools_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this school. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["School"];
                "application/x-www-form-urlencoded": components["schemas"]["School"];
                "multipart/form-data": components["schemas"]["School"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["School"];
                };
            };
        };
    };
    schools_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this school. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    schools_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this school. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedSchool"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedSchool"];
                "multipart/form-data": components["schemas"]["PatchedSchool"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["School"];
                };
            };
        };
    };
    users_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedUserList"];
                };
            };
        };
    };
    users_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["User"];
                "application/x-www-form-urlencoded": components["schemas"]["User"];
                "multipart/form-data": components["schemas"]["User"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    users_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this user. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    users_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this user. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["User"];
                "application/x-www-form-urlencoded": components["schemas"]["User"];
                "multipart/form-data": components["schemas"]["User"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    users_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this user. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    users_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this user. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedUser"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedUser"];
                "multipart/form-data": components["schemas"]["PatchedUser"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
}
