# Generated by Django 5.2.7 on 2026-03-20 19:36

from django.db import migrations

def purge_legacy_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    # Permanently delete all legacy roles from the live database
    # Keep only the unified abstractions
    Group.objects.exclude(name__in=['Admin', 'Manager', 'Viewer', 'Parent']).delete()

class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0002_user_firebase_uid_alter_school_name_and_more"),
    ]

    operations = [
        migrations.RunPython(purge_legacy_groups, reverse_code=migrations.RunPython.noop),
    ]
