# Generated by Django 5.2.7 on 2026-03-20 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buses", "0009_remove_bus_school_remove_route_school_and_more"),
        ("schools", "0003_force_repair_db_schema"),
        ("students", "0003_remove_student_school"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transporter",
            name="school",
        ),
        migrations.RemoveField(
            model_name="user",
            name="school",
        ),
        migrations.RemoveField(
            model_name="transporter",
            name="organisation",
        ),
        migrations.RemoveField(
            model_name="user",
            name="transporter",
        ),
        migrations.RemoveField(
            model_name="user",
            name="google_id",
        ),
        migrations.RemoveField(
            model_name="user",
            name="role",
        ),
        migrations.AlterField(
            model_name="organisation",
            name="org_type",
            field=models.CharField(
                choices=[
                    ("school", "School / Education"),
                    ("bus_agency", "Independent Bus Agency / Transporter"),
                    ("carpool", "Carpool Agency"),
                    ("corporate", "Corporate Shuttle"),
                ],
                default="bus_agency",
                max_length=30,
            ),
        ),
        migrations.DeleteModel(
            name="School",
        ),
        migrations.DeleteModel(
            name="Transporter",
        ),
    ]
