# Generated by Django 5.2.7 on 2026-03-21 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0004_remove_transporter_school_remove_user_school_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organisation",
            name="parent",
        ),
    ]
