# Generated by Django on 2026-03-21

from django.db import migrations

def clear_old_firebase_uids(apps, schema_editor):
    """
    Clears all existing firebase_uid values so the 'Register Once' 
    logic can capture new UIDs after the project migration.
    """
    User = apps.get_model('schools', 'User')
    User.objects.all().update(firebase_uid='')

class Migration(migrations.Migration):
    dependencies = [
        ('schools', '0005_remove_organisation_parent'),
    ]

    operations = [
        migrations.RunPython(clear_old_firebase_uids),
    ]
