# Generated by Django 5.2.7 on 2026-03-21 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0006_clear_old_firebase_uids"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="schools.organisation",
            ),
        ),
    ]
