# Generated by Django 4.2.7 on 2026-03-11 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('boarding', 'Boarding'), ('alighting', 'Alighting')], max_length=20)),
                ('confidence', models.FloatField()),
                ('clip_url', models.URLField(blank=True)),
                ('frame_url', models.URLField(blank=True)),
                ('notified', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
