# Generated by Django 5.2.7 on 2026-03-20 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0002_user_firebase_uid_alter_school_name_and_more"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="parent",
            name="organisation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parents_list",
                to="schools.organisation",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="allocated_to",
            field=models.ManyToManyField(
                blank=True, related_name="allocated_students", to="schools.organisation"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="organisation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students",
                to="schools.organisation",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students",
                to="schools.school",
            ),
        ),
    ]
