# Generated by Django 5.2.7 on 2026-03-20 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_parent_organisation_student_allocated_to_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="school",
        ),
    ]
