# Generated by Django 5.2.7 on 2026-03-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gps", "0004_gpspoint_heading"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gpspoint",
            name="heading",
            field=models.FloatField(
                default=0, help_text="Direction of travel in degrees (0-360)"
            ),
        ),
        migrations.AlterField(
            model_name="gpspoint",
            name="ignition",
            field=models.BooleanField(default=False),
        ),
    ]
