# Generated by Django 5.2.7 on 2026-03-22 14:55

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buses", "0012_busallocationlog_remove_busallocation_is_active"),
        ("gps", "0005_alter_gpspoint_heading_alter_gpspoint_ignition"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gpspoint",
            name="timestamp",
            field=models.DateTimeField(),
        ),
        migrations.AddIndex(
            model_name="gpspoint",
            index=django.contrib.postgres.indexes.BrinIndex(
                fields=["timestamp"], name="gps_gpspoin_timesta_eb9802_brin"
            ),
        ),
    ]
