# Generated by Django 5.2.7 on 2026-03-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buses", "0004_bus_gps_imei"),
    ]

    operations = [
        migrations.AddField(
            model_name="camera",
            name="stream_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
