# Generated by Django 5.2.7 on 2026-03-20 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buses", "0006_alter_bus_status"),
        ("schools", "0002_user_firebase_uid_alter_school_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bus",
            options={"verbose_name": "Vehicle", "verbose_name_plural": "Vehicles"},
        ),
        migrations.AddField(
            model_name="bus",
            name="fuel_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("diesel", "Diesel"),
                    ("petrol", "Petrol"),
                    ("electric", "Electric"),
                    ("cng", "CNG"),
                    ("hybrid", "Hybrid"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="bus",
            name="has_ac",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="bus",
            name="has_cctv",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="bus",
            name="make",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="bus",
            name="manufacture_year",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bus",
            name="model_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="bus",
            name="organisation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="buses",
                to="schools.organisation",
            ),
        ),
        migrations.AddField(
            model_name="bus",
            name="seating_capacity",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bus",
            name="vehicle_type",
            field=models.CharField(
                choices=[
                    ("bus", "Bus"),
                    ("minibus", "Minibus"),
                    ("van", "Van"),
                    ("tempo", "Tempo Traveller"),
                    ("sedan", "Sedan / Car"),
                    ("electric_bus", "Electric Bus"),
                    ("truck", "Truck"),
                ],
                default="bus",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="route",
            name="organisation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="routes",
                to="schools.organisation",
            ),
        ),
        migrations.AlterField(
            model_name="bus",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="buses",
                to="schools.school",
            ),
        ),
        migrations.AlterField(
            model_name="bus",
            name="status",
            field=models.CharField(
                choices=[
                    ("moving", "Moving"),
                    ("idle", "Idle"),
                    ("ignition_off", "Ignition Off"),
                    ("offline", "Offline"),
                ],
                default="offline",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="routes",
                to="schools.school",
            ),
        ),
    ]
