# Generated by Django 5.2.7 on 2026-03-20 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buses", "0007_alter_bus_options_bus_fuel_type_bus_has_ac_and_more"),
        ("schools", "0002_user_firebase_uid_alter_school_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bus",
            name="allocated_to",
            field=models.ManyToManyField(
                blank=True, related_name="allocated_buses", to="schools.organisation"
            ),
        ),
        migrations.AddField(
            model_name="route",
            name="allocated_to",
            field=models.ManyToManyField(
                blank=True, related_name="allocated_routes", to="schools.organisation"
            ),
        ),
        migrations.AlterField(
            model_name="bus",
            name="organisation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_buses",
                to="schools.organisation",
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="organisation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_routes",
                to="schools.organisation",
            ),
        ),
    ]
