# Generated by Django 5.2.7 on 2026-03-20 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buses", "0008_bus_allocated_to_route_allocated_to_and_more"),
        ("schools", "0003_force_repair_db_schema"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bus",
            name="school",
        ),
        migrations.RemoveField(
            model_name="route",
            name="school",
        ),
        migrations.AlterField(
            model_name="bus",
            name="transporter",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"org_type": "bus_agency"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="operated_buses",
                to="schools.organisation",
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="transporter",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"org_type": "bus_agency"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="operated_routes",
                to="schools.organisation",
            ),
        ),
    ]
