# Generated by Django 5.2.7 on 2026-03-20 21:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buses", "0009_remove_bus_school_remove_route_school_and_more"),
        ("schools", "0004_remove_transporter_school_remove_user_school_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bus",
            name="allocated_to",
        ),
        migrations.RemoveField(
            model_name="route",
            name="allocated_to",
        ),
        migrations.CreateModel(
            name="BusAllocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("view", "View Only"),
                            ("edit", "Edit Details"),
                            ("admin", "Full (Can Share/Allocate)"),
                        ],
                        default="view",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="buses.bus",
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations_granted",
                        to="schools.organisation",
                    ),
                ),
                (
                    "granted_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations_received",
                        to="schools.organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bus Allocation",
                "verbose_name_plural": "Bus Allocations",
                "unique_together": {("bus", "granted_to")},
            },
        ),
    ]
