# Generated by Django 5.2.7 on 2026-03-20 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buses", "0010_remove_bus_allocated_to_remove_route_allocated_to_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="busallocation",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
