# Generated by Django 5.2.7 on 2026-03-20 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buses", "0011_busallocation_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusAllocationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bus_internal_id", models.CharField(max_length=50)),
                ("granted_by_name", models.CharField(max_length=255)),
                ("granted_to_name", models.CharField(max_length=255)),
                ("level", models.CharField(max_length=50)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("UPDATED", "Updated"),
                            ("DELETED", "Deleted"),
                        ],
                        max_length=10,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Allocation Ledger",
                "verbose_name_plural": "Allocation Ledger",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.RemoveField(
            model_name="busallocation",
            name="is_active",
        ),
    ]
